name: "Inport-to-DefectDojo"
description: "import scan results to DefectDojo"
author: "hoainamnv34"
inputs: 
  host:
    description: "host of DefectDojo"
    required: true
  product:
    description: "product name"
    required: true
  engagement:
    description: "engagement name"
    required: true
  scan:
    description: "Scan type"
    required: true
  is_new_import:
    description: "is new import (True/False)"
    default: "True"
  report:
    description: "Report for import"
    required: false
  token:
    description: "token for import"
    required: true
  # output:
  #   description: "Output format for results"
  #   default: "stdout"
runs:
  using: 'docker'
  image: 'Dockerfile'
  # entrypoint: sh
  args:
  # - -c
  - --host 
  - "${{ inputs.host }}" 
  - --product 
  - "${{ inputs.product }}"
  - --engagement
  - "${{ inputs.engagement }}"
  - --scan 
  - "${{ inputs.scan }}"
  - --report 
  - "${{ inputs.report }}"
  - --is_new
  - "${{ inputs.is_new_import }}"
  - --token
  - "${{ inputs.token }}"
