name: "Inport-to-DefectDojo"
description: "import scan results to DefectDojo"
author: "hoainamnv34"
inputs: 
  host:
    description: "host of DefectDojo"
    required: true
  product:
    description: "product name"
    required: true
  engagement:
    description: "engagement name"
    required: true
  scan:
    description: "Scan type"
    required: true
  report:
    description: "Report for import"
    required: true
  # output:
  #   description: "Output format for results"
  #   default: "stdout"
runs:
  using: 'docker'
  image: 'python:3.9-bullseye'
  entrypoint: sh
  args:
  - -c
  - python3 import_to_defect_dojo.py --host "${{ inputs.host }}" --product "${{ inputs.product }}" --engagement ${{ inputs.engagement }} --scan ${{ inputs.scan }} --report --scan ${{ inputs.report }}
  # - conftest test -o json -p "${{ inputs.policy }}" --all-namespaces --combine="${{ inputs.combine }}" ${{ inputs.files }} > report.json