name: "Import-to-DefectDojo"
description: "Import scan results to DefectDojo"
author: "hoainamnv34"
inputs: 
  host:
    description: "Host of DefectDojo"
    required: true
  product:
    description: "Product name"
    required: true
  engagement:
    description: "Engagement name"
    required: true
  scan:
    description: "Scan type"
    required: true
  is_new_import:
    description: "Is new import (True/False)"
    required: false
    default: "True"
  report:
    description: "Report for import"
    required: false
  token:
    description: "Token for import"
    required: true
  active:
    description: "Active status"
    required: false
    default: "False"
  verified:
    description: "Verified status"
    required: false
    default: "False"
  test_title:
    description: "Test title"
    required: false
  close_old_findings:
    description: "Close old findings"
    required: false
    default: "False"
  close_old_findings_product_scope:
    description: "Close old findings product scope"
    required: false
    default: "False"
  branch_tag:
    description: "Branch tag"
    required: false
  commit_hash:
    description: "Commit hash"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  # entrypoint: sh
  args:
  # - -c
  - --host 
  - "${{ inputs.host }}" 
  - --product 
  - "${{ inputs.product }}"
  - --engagement
  - "${{ inputs.engagement }}"
  - --scan 
  - "${{ inputs.scan }}"
  - --report 
  - "${{ inputs.report }}"
  - --is-new
  - "${{ inputs.is_new_import }}"
  - --token
  - "${{ inputs.token }}"
  - --active
  - "${{ inputs.active }}"
  - --verified
  - "${{ inputs.verified }}"
  - --test_title
  - "${{ inputs.test_title }}"
  - --close_old_findings
  - "${{ inputs.close_old_findings }}"
  - --close_old_findings_product_scope
  - "${{ inputs.close_old_findings_product_scope }}"
  - --branch_tag
  - "${{ inputs.branch_tag }}"
  - --commit_hash
  - "${{ inputs.commit_hash }}"
